#!/bin/bash
# Simple script to synchronize local directory with external
# server via ssh.
####################
# Written by Kirill O. <cyberstatar@gmail.com>
# Last update 14/02/2025
CONFIG="/etc/lib_sync.conf"

create_config() {
    read -p "Enter external server IP: " ip
    read -p "Enter username: " user
    read -p "Enter remote directory path: " libPath
    echo -e "ip=\"$ip\"\nuser=\"$user\"\nlibPath=\"$libPath\"" | sudo tee "$CONFIG" > /dev/null
    echo "Configuration saved to $CONFIG"
}

if [[ ! -f "$CONFIG" ]]; then
    echo "Config file not found. Let's create it."
    create_config
fi

source "$CONFIG" || { echo "Error: there is no file 'lib.conf'"; exit 1; }

[[ -z "$user" ]] && { echo "User is not defined"; exit 2; }
[[ -z "$ip" ]] && { echo "IP is not defined"; exit 3; }
[[ -d "$libPath"  ]] || { echo "$libPath is not a directory"; exit 5; } 

rsync -avu "$user@$ip":"$libPath/" "$libPath/" || { echo "Synchronization error"; exit 4; }

rsync -avu "$libPath/" "$user@$ip":"$libPath/"
